### ISSUE TITLE
セルの中の要素の位置揃えがちょっとわかりにくかったです

### ISSUE THREAD

**Issue by kurudrive** [t-hamano/flexible-table-block#11]
※ 総じてとんでもなく素晴らしいです。
あくまで無理やりケチをつけてるレベルの個人的感想です。

![固定ページを編集-‹-delasal-kusunoki-デラサル楠-愛知県名古屋市の室内フットサル場-—-WordPress (4)](https://user-images.githubusercontent.com/3272660/137180322-12ca63c1-aca0-4410-b327-277073c7d2e1.png)

**Comment by t-hamano** [comment]
ツールバーアイコンの方は、テーブル自体の左右揃えをコントロールするものとなります。
（例えばテーブルが50%幅だったとして、中央または右寄せにしたい時など）
テーブルの左右揃えとは分かりづらいので、文言の変更等を検討させていただきます。
