### ISSUE TITLE
英単語が途中で改行されてしまうので word-break に break-all を指定しないでほしい

### ISSUE THREAD

**Issue by waviaei** [t-hamano/flexible-table-block#138]
v2.7.0 から変更があったようなのですが、`word-break` に `break-all` を指定しないでほしいです。
https://github.com/t-hamano/flexible-table-block/commit/85032e95f0aebad3539e11687e71654f053ccb97

`beak-all` にするとCJK以外でも単語の途中で改行をしてしまいます。
https://developer.mozilla.org/ja/docs/Web/CSS/word-break

**Comment by waviaei** [comment]
`word-break: break-word` は deprecate されています。

https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
> Note: While word-break: break-word is deprecated, it has the same effect, when specified, as word-break: normal and overflow-wrap: anywhere — regardless of the actual value of the [overflow-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) property.

なので上記で記されているように下記の方がベターだと思います。

```
word-break: normal;
overflow-wrap: anywhere;
```

加えて、英語などでは1つの単語を2行に分けざるをえない場合、ハイフンでつなぎます。例えば

```
WordP-
ress
```

これを行うスタイルで [hyphens](https://developer.mozilla.org/ja/docs/Web/CSS/hyphens) というのがあるので、これを足して下記でどうでしょうか？

```
word-break: normal;
overflow-wrap: anywhere;
hyphens: auto;
```

**Comment by t-hamano** [comment]
> なので上記で記されているように下記の方がベターだと思います。

ありがとうございます、この方向で問題無いか調整してみます。

> これを行うスタイルで [hyphens](https://developer.mozilla.org/ja/docs/Web/CSS/hyphens) というのがあるので、これを足して下記でどうでしょうか？

こちらに関しては、必要以上にデフォルトスタイルを上書きしたくないという事と、手動（`manual`）でコントロールしたい人もいるかもしれないので、ユーザ（テーマ）側のコントロールに委ねたいと思います。
