### ISSUE TITLE
Responsive scrolling on mobile

### ISSUE THREAD

**Issue by corliavt** [t-hamano/flexible-table-block#150]
Hello,

I'm not able to activate the scrolling function for my table on mobile/ Desktop - can you confirm the setting for me.  I've added screen grabs of the setting I currently have.

On mobile the copy presses up into horrible lines instead of neatly scrolling across.  See screengrab (4)
https://effectphotonics.com/points-of-view/improving-edge-computing-with-coherent-optical-systems-on-chip/

![1](https://user-images.githubusercontent.com/117648044/200306953-b2d9a3f2-e977-4653-adad-ff1634d78c45.jpg)
![2](https://user-images.githubusercontent.com/117648044/200306965-b92bf121-a00f-41a5-860b-f6ac5d25dd19.jpg)
![3](https://
![4](https://user-images.githubusercontent.com/117648044/200307296-509a9e09-9a8c-4e3d-a5fc-ae8fca7e0b00.jpg)
user-images.githubusercontent.com/117648044/200306981-1e8a226e-9dbe-47c1-9798-8338763731f3.jpg)

**Comment by t-hamano** [comment]
To enable scrolling, the table width must be intentionally larger than 100% of the content width.
For example, the following settings are useful

- Table Width: 1000px;
- Table Min Width: 1000px;
- Table Min Width;: 120%;

Try to find the best value for your site and table content.

**Comment by corliavt** [comment]
Hello,

Thank you, the scrolling is now live, it doesn't allow me to scroll to the end of the table on mobile.  Is there a setting I need to change?

https://effectphotonics.com/points-of-view/improving-edge-computing-with-coherent-optical-systems-on-chip/ 

![5](https://user-images.githubusercontent.com/117648044/200320566-a8abb18a-66b6-45b7-9bef-6f5ed592221c.jpg)

**Comment by t-hamano** [comment]
I checked your site and I believe that putting it out of the group block will solve the problem.

**Comment by t-hamano** [comment]
I would like to close this issue, but if you have any problems with this plugin, please comment anytime.
