### ISSUE TITLE
Instant (cell content selection) at (cell selection)

### ISSUE THREAD

**Issue by Rodi9999** [t-hamano/flexible-table-block#185]
When the user moves from a cell to another cell (_using the keyboard's directional keys or the mouse left button_), please let the whole content of the new cell be selected, so that it is ready for instant replacing/typing. This will improve the speed of editing tables. 

Currently, every time I want to edit a cell in a table, I have to click (Ctrl+A) inside the cell to select the whole text inside it before typing the new content. Clicking (Ctrl+A) becomes frustrating when there are many cells to be edited in a single table.

Take Microsoft Excel as an example please: when moving to a cell that already has content, it is possible to replace the content by instant typing.

I hope the feature is feasible and considered! 
And thank you so much for providing this invaluable plugin!

**Comment by t-hamano** [comment]
Thank you for your suggestion.

>When the user moves from a cell to another cell (using the keyboard's directional keys or the mouse left button), please let the whole content of the new cell be selected, so that it is ready for instant replacing/typing.

I'm not currently considering implementing this behavior to align with the core table block behavior.

However, Flexible Table Block allows you to opt-in to cell movement using the Tab key. If you use the Tab key to move, all text in the cell will be selected.


https://github.com/t-hamano/flexible-table-block/assets/54422211/c2803823-368b-442e-9a7d-ed86ebea554b

**Comment by Rodi9999** [comment]
Thank you for the quick response.

I did not know about the Tab key option. It improves the speed of editing very well and I will take it as a solution. Thank you!

Kind regards,

**Comment by Rodi9999** [comment]
Thank you for the quick response.

I did not know about the Tab key option. It improves the speed of editing very well and I will take it as a solution. Thank you!

Kind regards,
