### ISSUE TITLE
入力内容がラベルで見えないので、もう少し見えた方が良いかなと思いました。

### ISSUE THREAD

**Issue by kurudrive** [t-hamano/flexible-table-block#9]
※ 総じてとんでもなく素晴らしいです。
あくまで無理やりケチをつけてるレベルの個人的感想です。

![固定ページを編集-‹-delasal-kusunoki-デラサル楠-愛知県名古屋市の室内フットサル場-—-WordPress (2)](https://user-images.githubusercontent.com/3272660/137177076-a0387f44-aba2-4db0-99d3-3ba595355d7d.png)

**Comment by t-hamano** [comment]
- ボタンを小さめに変更
- 左右のHTMLタグ（`<` / `>` ）を除去
